export const mockAPIResponse = [
  {
    firstName: "Sai",
    lastName: "Ram",
    email: "test@gmail.com",
    mobile: "99999999999",
    file: "",
  },
  {
    firstName: "Sai",
    lastName: "Ram",
    email: "test@gmail.com",
    mobile: "99999999999",
    file: "",
  },
  {
    firstName: "Sai",
    lastName: "Ram",
    email: "test@gmail.com",
    mobile: "99999999999",
    file: "",
  },
  {
    firstName: "Sai",
    lastName: "Ram",
    email: "test@gmail.com",
    mobile: "99999999999",
    file: "",
  },
  {
    firstName: "Sai",
    lastName: "Ram",
    email: "test@gmail.com",
    mobile: "99999999999",
    file: "",
  },
  {
    firstName: "Sai",
    lastName: "Ram",
    email: "test@gmail.com",
    mobile: "99999999999",
    file: "",
  },
  {
    firstName: "Sai",
    lastName: "Ram",
    email: "test@gmail.com",
    mobile: "99999999999",
    file: "",
  },
  {
    firstName: "Sai",
    lastName: "Ram",
    email: "test@gmail.com",
    mobile: "99999999999",
    file: "",
  },
  {
    firstName: "Sai",
    lastName: "Ram",
    email: "test@gmail.com",
    mobile: "99999999999",
    file: "",
  },
];
